### ISSUE TITLE
mixed use of code snippets without specific TODO marker reduces clarity

### ISSUE THREAD

**Issue by amgando** [Devbootcamp/snitching-on-sinatra#3]
@dreeve, here's an idea: 

the "work to do" snippets in this challenge look a lot like "sample output" snippets. same thing with all of our challenges, actually :wink:

i believe students are moving as quickly as possible through challenge text and this *mixed use* of code snippets (student input / system output) slows students down.  at each code block they have to ask and answer the same question *"should i type this in or look for this on my screen?"*.

instead, we might consider a specific call to action like the examples below.  most programming books do something similar where, in the book preface, they introduce a key for all symbols then use them throughout.

i picked two reasonable icons as examples from this list: http://www.emoji-cheat-sheet.com/

:hand: type the following line into your console
```text
gem install sinatra
```

---

:mag: notice the following output in your terminal
```text
== Sinatra (v1.4.6) has taken the stage on 4567 for development with backup from Thin
Thin web server (v1.6.2 codename Doc Brown)
Maximum connections set to 1024
Listening on localhost:4567, CTRL+C to stop
```

---

:hand: add the following lines to your `sinatra.rb` file
```ruby
get '/' do
  "Hello world!"
end
```

**Comment by dreeve** [comment]
I've been experimenting with adding emoji to part 2 of the tutorial. I noticed that adding a :hand: for each thing to type in was overwhelming and actually seemed a lot harder to read for me.

Instead, I put a [note](https://github.com/Devbootcamp/snitching-on-sinatra/blob/part2/part2.md#emoji-key) that code snippets are things to type in unless otherwise indicated, which keeps the noise down quite a bit.

**Comment by dreeve** [comment]
I added emoji to parts 1 and 2, mostly to indicate when the student should type and when they should be reading instead!

https://github.com/Devbootcamp/snitching-on-sinatra/blob/master/part2.md

**Comment by amgando** [comment]
looks awesome man. nicely done.
